services:
  PACT-BROKER-POSTGRES:
    image: postgres:latest
    container_name: Postgres_DB
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  PACT-BROKER:
    image: pactfoundation/pact-broker:latest
    container_name: Pact_Broker
    build: .
    ports:
      - "9292:9292"
    depends_on:
      - PACT-BROKER-POSTGRES
    environment:
      PACT_BROKER_DATABASE_HOST: PACT-BROKER-POSTGRES
      PACT_BROKER_DATABASE_NAME: postgres
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_LOG_LEVEL: DEBUG

volumes:
  postgres-volume: